# Generated by Django 4.2.7 on 2023-12-01 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('craftsmanAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftsman',
            options={'verbose_name_plural': 'craftsmen'},
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
