# Generated by Django 4.2.7 on 2023-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmanAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='craftsman',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/craftsmen/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects/'),
        ),
    ]
