# Generated by Django 4.2.7 on 2023-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmanAPI', '0002_alter_craftsman_options_alter_craftsman_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
