# Generated by Django 4.2.7 on 2024-03-01 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmanAPI', '0007_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craftsmanAPI.visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/visitor/'),
        ),
    ]
