# Generated by Django 4.2.7 on 2024-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftsmanAPI', '0008_alter_project_description_alter_review_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
